# Site settings
title: Projects
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/projects"
url: "http://famer.github.io/" # the base hostname & protocol for your site
#twitter_username: famer	
github_username:  famer

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "app" 
    values:
      type: app
      layout: "app"
