# Site settings
title: Timur T. Projects House
#email: your-email@domain.com
#description: Projects House
baseurl: "/projects"
url: "http://famer.github.io/" # the base hostname & protocol for your site
#twitter_username: famer	
github_username:  famer

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "app" 
    values:
      type: app
      layout: "app"
